version: '3'

services:
  scylla:
    image: scylladb/scylla:3.0.3
    networks:
      - scylla
    volumes:
      - ./data/scylla:/var/lib/scylla
    command: "--smp 1 --memory 256M"

  cassandra:
    image: cassandra:latest
    networks:
      - scylla
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  spark-master:
    image: gettyimages/spark:2.3.1-hadoop-3.0
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: spark-master
    networks:
      - scylla
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./data/spark-master:/tmp/data
      - ./target/scala-2.11:/jars
      - ./:/app

  spark-worker:
    image: gettyimages/spark:2.3.1-hadoop-3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1024m
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: spark-worker
    networks:
      - scylla
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./data/spark-worker:/tmp/data
    depends_on:
      - spark-master

networks:
  scylla:
